"""
Django settings for awn project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Base URL for constructing absolute URLs (configurable via environment variable)
BASE_URL = os.environ.get('BASE_URL', 'http://localhost:8000')

# Platform URL for email links
PLATFORM_URL = os.environ.get('PLATFORM_URL', 'https://awn-three.vercel.app')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)n0n8on81l1x+5_szj^0)3m!boj4g^=j3so$x+qk-n2z_&a!)2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # Set to False in production

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS headers for frontend access
    'awn',  
    'api', 
    'rest_framework',  
    'rest_framework_simplejwt', 
    'rest_framework_simplejwt.token_blacklist', 
    'django_extensions',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'awn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Added templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'awn.wsgi.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'awn',         
        'USER': 'postgres',           
        'PASSWORD': 'Awn@db.5200!!', 
        'HOST': '109.61.81.34',                  
        'PORT': '5432',                       
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication', 
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer', 
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




STATIC_URL = 'static/'



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# settings.py

from django.utils.translation import gettext_lazy as _

LANGUAGE_CODE = 'en'  # اللغة الافتراضية للعربية

LANGUAGES = (
    ('ar', _('Arabic')),   # إضافة اللغة العربية
    ('en', _('English')),  # خيار: يمكن إضافة الإنجليزية أو لغات أخرى
)

LOCALE_PATHS = [
    BASE_DIR / 'locale',  # مسار ملفات الترجمة
]

LANGUAGE_BIDI = True  # لأن العربية لغة تُكتب من اليمين لليسار

AUTH_USER_MODEL = 'api.User'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# إعدادات البريد الإلكتروني
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'awnpaltform@gmail.com'  
EMAIL_HOST_PASSWORD = 'ivgiuriekdhepasz'  
DEFAULT_FROM_EMAIL = 'AWN Platform <awnpaltform@gmail.com>'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Base URL for building absolute URLs - configured at top of file with environment variable

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "https://preview--chime-comms.lovable.app",
    "https://chime-comms.lovable.app", 
    "https://lovable.app",
    "http://localhost:3000",
    "https://localhost:3000",
    "http://localhost:3001",
    "https://localhost:3001",
    "http://localhost:3002",
    "http://127.0.0.1:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://127.0.0.1:3002",
    "https://awn-three.vercel.app",
    "http://mrs.infnet.tech",
    "https://mrs.infnet.tech",
    "https://mrs.infnet.tech:8001",
    "http://infnet.tech",
    "https://infnet.tech",
]

# Allow any Vercel preview domains
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]

CORS_ALLOW_CREDENTIALS = True

# Allow these origins to make state-changing requests (Django CSRF checks)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://localhost:3000",
    "http://localhost:3001",
    "https://localhost:3001",
    "http://localhost:3002",
    "https://localhost:3002",
    "https://awn-three.vercel.app",
    "https://awn-aao5ksjjj-ahmedalabadlas-projects.vercel.app",
    "http://mrs.infnet.tech",
    "https://mrs.infnet.tech",
    "https://mrs.infnet.tech:8001",
    "http://infnet.tech",
    "https://infnet.tech",
]

CORS_ALLOW_ALL_ORIGINS = DEBUG  # Allow all in development to unblock testing

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

