# Generated by Django 5.2.5 on 2025-08-16 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, help_text='اسم المستخدم الكامل', max_length=255, verbose_name='الاسم')),
                ('email', models.EmailField(help_text='البريد الإلكتروني الفريد للمستخدم', max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('role', models.CharField(choices=[('institution', 'مؤسسة'), ('admin', 'مدير'), ('user', 'مستخدم')], default='user', help_text='دور المستخدم في النظام', max_length=20, verbose_name='الدور')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان الإعلان', max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(help_text='وصف تفصيلي للإعلان', verbose_name='الوصف')),
                ('category', models.CharField(choices=[('food', 'غذائية'), ('medical', 'طبية'), ('health', 'صحية'), ('education', 'تعليمية'), ('technology', 'تقنية'), ('sports', 'رياضية'), ('cultural', 'ثقافية'), ('general', 'عامة')], default='general', help_text='فئة الإعلان', max_length=20, verbose_name='الفئة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('archived', 'مؤرشف')], default='draft', help_text='حالة الإعلان الحالية', max_length=20, verbose_name='الحالة')),
                ('is_pinned', models.BooleanField(default=False, help_text='هل الإعلان مثبت في الأعلى؟', verbose_name='مثبت')),
                ('publish_date', models.DateTimeField(blank=True, help_text='تاريخ نشر الإعلان (اختياري)', null=True, verbose_name='تاريخ النشر')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية الإعلان (اختياري)', null=True, verbose_name='تاريخ الانتهاء')),
                ('attachment', models.FileField(blank=True, help_text='ملف مرفق مع الإعلان (اختياري)', upload_to='announcements/', verbose_name='المرفق')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='عدد مرات مشاهدة الإعلان', verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('author', models.ForeignKey(help_text='المستخدم الذي أنشأ الإعلان', on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='المؤلف')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('in_review', 'قيد المراجعة'), ('withdrawn', 'منسحب')], default='pending', help_text='حالة طلب التقديم', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, help_text='ملاحظات من الإدارة حول الطلب', verbose_name='ملاحظات إدارية')),
                ('rejection_reason', models.TextField(blank=True, help_text='سبب رفض الطلب (في حالة الرفض)', verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('announcement', models.ForeignKey(help_text='الإعلان المتقدم عليه', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.announcement', verbose_name='الإعلان')),
                ('user', models.ForeignKey(help_text='المستخدم المتقدم', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب تقديم',
                'verbose_name_plural': 'طلبات التقديم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='وصف تفصيلي للمشكلة أو الاستفسار', verbose_name='وصف المشكلة')),
                ('type', models.CharField(choices=[('technical', 'مشكلة تقنية'), ('account', 'مشكلة في الحساب'), ('general', 'استفسار عام'), ('complaint', 'شكوى'), ('suggestion', 'اقتراح')], default='general', help_text='نوع طلب الدعم', max_length=20, verbose_name='نوع الطلب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('user', models.ForeignKey(help_text='المستخدم الذي أرسل طلب الدعم', on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب دعم',
                'verbose_name_plural': 'طلبات الدعم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='نص الإشعار المرسل للمستخدم', verbose_name='رسالة الإشعار')),
                ('read_status', models.BooleanField(default=False, help_text='هل تم قراءة الإشعار؟', verbose_name='حالة القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('user', models.ForeignKey(help_text='المستخدم المرسل إليه الإشعار', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='الاسم الرسمي للمؤسسة', max_length=255, verbose_name='اسم المؤسسة')),
                ('description', models.TextField(blank=True, help_text='وصف تفصيلي عن المؤسسة وأنشطتها', verbose_name='وصف المؤسسة')),
                ('website', models.URLField(blank=True, help_text='رابط الموقع الرسمي للمؤسسة', verbose_name='الموقع الإلكتروني')),
                ('phone', models.CharField(blank=True, help_text='رقم الهاتف الرسمي للمؤسسة', max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, help_text='البريد الإلكتروني الرسمي للمؤسسة', max_length=254, verbose_name='البريد الإلكتروني')),
                ('location', models.CharField(blank=True, help_text='العنوان أو الموقع الجغرافي للمؤسسة', max_length=255, verbose_name='الموقع')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, help_text='تقييم المؤسسة من 0.00 إلى 5.00', max_digits=3, verbose_name='التقييم')),
                ('verified', models.BooleanField(default=False, help_text='هل المؤسسة محققة من قبل الإدارة؟', verbose_name='محقق')),
                ('is_active', models.BooleanField(default=True, help_text='هل المؤسسة نشطة حالياً؟', verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(help_text='المستخدم المسؤول عن المؤسسة', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المسؤول')),
            ],
            options={
                'verbose_name': 'مؤسسة',
                'verbose_name_plural': 'المؤسسات',
                'ordering': ['-rate', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='المؤسسة التي ينتمي إليها الإعلان (اختياري)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.organization', verbose_name='المؤسسة'),
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_docs', models.FileField(blank=True, help_text='وثائق تسجيل المؤسسة الرسمية', upload_to='organizations/registration/', verbose_name='وثائق التسجيل')),
                ('financial_report', models.FileField(blank=True, help_text='التقارير المالية للمؤسسة', upload_to='organizations/financial/', verbose_name='التقرير المالي')),
                ('activity_proof', models.JSONField(blank=True, default=dict, help_text='بيانات JSON تحتوي على أدلة أنشطة المؤسسة', verbose_name='دليل النشاط')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.organization', verbose_name='المؤسسة')),
            ],
            options={
                'verbose_name': 'وثيقة مؤسسة',
                'verbose_name_plural': 'وثائق المؤسسات',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='تعليق أو ملاحظات حول الطلب', verbose_name='التعليق')),
                ('rating', models.PositiveSmallIntegerField(default=1, help_text='التقييم من 1 إلى 5', verbose_name='التقييم')),
                ('application', models.ForeignKey(help_text='طلب التقديم المراد تقييمه', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.application', verbose_name='طلب التقديم')),
            ],
            options={
                'verbose_name': 'تقييم',
                'verbose_name_plural': 'التقييمات',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='تاريخ إضافة الإعلان للمفضلة', verbose_name='تاريخ الإضافة')),
                ('announcement', models.ForeignKey(help_text='الإعلان المضاف للمفضلة', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.announcement', verbose_name='الإعلان')),
                ('user', models.ForeignKey(help_text='المستخدم الذي أضاف الإعلان للمفضلة', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مفضلة',
                'verbose_name_plural': 'المفضلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='عنوان IP للمشاهد (للمستخدمين غير المسجلين)', null=True, verbose_name='عنوان IP')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المشاهدة')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_views', to='api.announcement', verbose_name='الإعلان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewed_announcements', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مشاهدة إعلان',
                'verbose_name_plural': 'مشاهدات الإعلانات',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['announcement', '-viewed_at'], name='api_announc_announc_6bd741_idx'), models.Index(fields=['user', '-viewed_at'], name='api_announc_user_id_b4b3da_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-created_at'], name='api_applica_status_1e3c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'status'], name='api_applica_user_id_32dae2_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='unique_application'),
        ),
        migrations.AddIndex(
            model_name='helpsupport',
            index=models.Index(fields=['type', '-created_at'], name='api_helpsup_type_931d36_idx'),
        ),
        migrations.AddIndex(
            model_name='helpsupport',
            index=models.Index(fields=['user', '-created_at'], name='api_helpsup_user_id_9bda9f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_status'], name='api_notific_user_id_847a59_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='api_notific_created_ae9e55_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['verified', 'is_active'], name='api_organiz_verifie_0ca865_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['-rate'], name='api_organiz_rate_6fb653_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'category'], name='api_announc_status_1c373f_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['publish_date'], name='api_announc_publish_67e0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_pinned', '-created_at'], name='api_announc_is_pinn_f64d1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('application',), name='unique_application_review'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', '-created_at'], name='api_userfav_user_id_4c4bbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'announcement'), name='unique_user_favorite'),
        ),
    ]
