# Generated by Django 5.2 on 2025-08-18 11:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the announcement category', max_length=100, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, help_text='Full user name', max_length=255, verbose_name='Name')),
                ('email', models.EmailField(help_text='Unique email address for the user', max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text="User's phone number", max_length=14, verbose_name='Phone Number')),
                ('is_active', models.BooleanField(default=True, help_text='Is the user active?', verbose_name='Active')),
                ('role', models.CharField(choices=[('institution', 'Institution'), ('admin', 'Admin'), ('user', 'User')], default='user', help_text='User role in the system', max_length=20, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when the user was created', verbose_name='Creation Date')),
                ('ubdated_at', models.DateTimeField(auto_now=True, help_text='Date when the user was last updated', verbose_name='Update Date')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement title', max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed description of the announcement', verbose_name='Description')),
                ('start_date', models.DateTimeField(blank=True, help_text='Announcement start date (optional)', null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, help_text='Announcement end date (optional)', null=True, verbose_name='End Date')),
                ('url', models.URLField(default='https://example.com', help_text='Link to the announcement details', verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('AnnouncementCategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.announcementcategory')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_review', 'In Review'), ('withdrawn', 'Withdrawn')], default='pending', help_text='Application status', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the application', verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Application Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('announcement', models.ForeignKey(help_text='Announcement being applied to', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.announcement', verbose_name='Announcement')),
                ('user', models.ForeignKey(help_text='User applying', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelpSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Detailed description of the issue or inquiry', verbose_name='Issue Description')),
                ('type', models.CharField(choices=[('account', 'Account Issue'), ('general', 'General Inquiry'), ('complaint', 'Complaint')], default='general', help_text='Type of support request', max_length=20, verbose_name='Request Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Send Date')),
                ('user', models.ForeignKey(help_text='User who sent the support request', on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Support Request',
                'verbose_name_plural': 'Support Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Notification', max_length=50)),
                ('message', models.TextField(help_text='Notification text sent to user', verbose_name='Notification Message')),
                ('read_status', models.BooleanField(default=False, help_text='Has the notification been read?', verbose_name='Read Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Send Date')),
                ('user', models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official organization name', max_length=255, verbose_name='Organization Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of organization and its activities', verbose_name='Organization Description')),
                ('website', models.URLField(blank=True, help_text="Organization's official website link", verbose_name='Website')),
                ('contact_phone', models.CharField(blank=True, help_text="Organization's official phone number", max_length=14, verbose_name='Phone Number')),
                ('contact_email', models.EmailField(blank=True, help_text="Organization's official email address", max_length=254, verbose_name='Email')),
                ('location', models.CharField(blank=True, help_text="Organization's address or geographical location", max_length=255, verbose_name='Location')),
                ('rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('verified', models.BooleanField(default=False, help_text='Is the organization verified by admin?', verbose_name='Verified')),
                ('is_active', models.BooleanField(default=True, help_text='Is the organization currently active?', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registration Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('user', models.ForeignKey(help_text='User responsible for the organization', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Responsible User')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['-rate', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization the announcement belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.organization', verbose_name='Organization'),
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_docs', models.FileField(blank=True, help_text='Official organization registration documents', upload_to='organizations/registration/', verbose_name='Registration Documents')),
                ('financial_report', models.FileField(blank=True, help_text='Organization financial reports', upload_to='organizations/financial/', verbose_name='Financial Report')),
                ('activity_proof', models.JSONField(blank=True, default=dict, help_text='JSON data containing organization activity proofs', verbose_name='Activity Proof')),
                ('address_proof', models.FileField(blank=True, help_text='Organization financial reports', upload_to='organizations/address/', verbose_name='Financial Report')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Organization Document',
                'verbose_name_plural': 'Organization Documents',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, help_text='Comment or notes about the application', verbose_name='Comment')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(help_text='Application to be reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.application', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date announcement was added to favorites', verbose_name='Addition Date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when favorite was last updated', verbose_name='Update Date')),
                ('announcement', models.ForeignKey(help_text='Announcement added to favorites', on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.announcement', verbose_name='Announcement')),
                ('user', models.ForeignKey(help_text='User who added announcement to favorites', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', '-created_at'], name='api_applica_status_1e3c9a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'status'], name='api_applica_user_id_32dae2_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='unique_application'),
        ),
        migrations.AddIndex(
            model_name='helpsupport',
            index=models.Index(fields=['type', '-created_at'], name='api_helpsup_type_931d36_idx'),
        ),
        migrations.AddIndex(
            model_name='helpsupport',
            index=models.Index(fields=['user', '-created_at'], name='api_helpsup_user_id_9bda9f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_status'], name='api_notific_user_id_847a59_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='api_notific_created_ae9e55_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['verified', 'is_active'], name='api_organiz_verifie_0ca865_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['-rate'], name='api_organiz_rate_6fb653_idx'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['-created_at'], name='api_announc_created_a72ad4_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('application',), name='unique_application_review'),
        ),
        migrations.AddIndex(
            model_name='userfavorite',
            index=models.Index(fields=['user', '-created_at'], name='api_userfav_user_id_4c4bbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='userfavorite',
            constraint=models.UniqueConstraint(fields=('user', 'announcement'), name='unique_user_favorite'),
        ),
    ]
