# Generated by Django 5.2.5 on 2025-08-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('organization', 'Organization'), ('admin', 'Admin'), ('user', 'User')], default='user', help_text='User role in the system', max_length=20, verbose_name='Role'),
        ),
    ]
