# Generated by Django 5.2.5 on 2025-08-26 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_helpsupport_priority_helpsupport_target_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsupport',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='helpsupport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned to Organization'), ('waiting_org_response', 'Waiting for Organization Response'), ('waiting_admin_response', 'Waiting for Admin Response'), ('closed', 'Closed')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='type',
            field=models.CharField(choices=[('account', 'Account Issue'), ('general', 'General Inquiry'), ('complaint', 'Complaint')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
