# Generated by Django 5.2.5 on 2025-08-20 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_organization_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='AnnouncementCategory',
        ),
        migrations.AddField(
            model_name='announcement',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes about the announcement approval/rejection', verbose_name='Admin Notes'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(default=1, help_text='Announcement category', on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='api.announcementcategory', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='User who created this announcement', on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='draft', help_text='Announcement approval status', max_length=20, verbose_name='Status'),
        ),
    ]
