# Generated by Django 5.2.5 on 2025-08-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_announcement_announcementcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Custom organization name (for admin use)', max_length=255, null=True, verbose_name='Organization Name'),
        ),
    ]
