# Generated by Django 5.2.5 on 2025-08-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_date_joined_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
