# Generated by Django 5.2.5 on 2025-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_helpsupport_admin_response_helpsupport_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpsupport',
            old_name='admin_response',
            new_name='reply',
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('waiting_response', 'Waiting for Response'), ('closed', 'Closed')], default='pending', max_length=30),
        ),
    ]
