# Generated by Django 5.2.5 on 2025-08-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_organization_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Is this application marked as favorite by the user?', verbose_name='Is Favorite'),
        ),
    ]
