# Generated by Django 5.2.5 on 2025-08-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_announcement_organization_name'),
    ]

    operations = [
        # This is a no-op migration since first_name and last_name
        # were never actually created in the database
        # We're just updating the model to explicitly set them to None
    ]