# Generated by Django 5.2.5 on 2025-08-20 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_remove_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text='Date when the user joined',
                verbose_name='Date Joined'
            ),
            preserve_default=False,
        ),
    ]