# Generated by Django 5.2.5 on 2025-08-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_add_date_joined'),
    ]

    operations = [
        # This is a no-op migration to sync the model state
        # The updated_at field already exists in the database
    ]