# Generated by Django 5.2.5 on 2025-08-26 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_admin_response_helpsupport_reply_and_more'),
    ]

    operations = [
    ]
