# Generated by Django 5.2.5 on 2025-08-26 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20250826_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date when the user joined', verbose_name='Date Joined'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when the user was created', verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date when the user was last updated', verbose_name='Update Date'),
        ),
    ]
