# Generated by Django 5.2.5 on 2025-08-26 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_is_staff_alter_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
