# Generated by Django 5.2.5 on 2025-08-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_user_date_joined'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_userfavorite RENAME COLUMN application_id TO announcement_id;",
            reverse_sql="ALTER TABLE api_userfavorite RENAME COLUMN announcement_id TO application_id;"
        ),
    ]
