# Generated by Django 5.2.5 on 2025-08-26 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20250826_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='application',
        ),
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_application',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='api_applica_user_id_32dae2_idx',
        ),
        migrations.RemoveField(
            model_name='application',
            name='is_favorite',
        ),
        migrations.AlterField(
            model_name='application',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Admin notes about the application review', verbose_name='Admin Notes'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the application', max_length=20, verbose_name='Application Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(help_text='User who submitted the application', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', '-created_at'], name='api_applica_user_id_effeb6_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['announcement', 'status'], name='api_applica_announc_1efd08_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('user', 'announcement'), name='unique_user_application'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
