# Generated by Django 5.2.5 on 2025-08-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_review_application_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
