# Generated by Django 5.2.5 on 2025-08-26 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Custom organization name (for admin use) if the announcement is not associated with an organization or non registered organization', max_length=255, null=True, verbose_name='Organization Name'),
        ),
        migrations.CreateModel(
            name='AnnouncementEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_title', models.CharField(help_text='Proposed new title', max_length=255, verbose_name='Proposed Title')),
                ('proposed_description', models.TextField(help_text='Proposed new description', verbose_name='Proposed Description')),
                ('proposed_start_date', models.DateTimeField(blank=True, help_text='Proposed new start date', null=True, verbose_name='Proposed Start Date')),
                ('proposed_end_date', models.DateTimeField(blank=True, help_text='Proposed new end date', null=True, verbose_name='Proposed End Date')),
                ('proposed_url', models.URLField(help_text='Proposed new URL', verbose_name='Proposed URL')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Edit request status', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about the edit request approval/rejection', verbose_name='Admin Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Date when the edit request was reviewed', null=True, verbose_name='Review Date')),
                ('original_announcement', models.ForeignKey(help_text='The announcement being requested for edit', on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='api.announcement', verbose_name='Original Announcement')),
                ('proposed_category', models.ForeignKey(help_text='Proposed new category', on_delete=django.db.models.deletion.CASCADE, to='api.announcementcategory', verbose_name='Proposed Category')),
                ('requested_by', models.ForeignKey(help_text='User who requested the edit', on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this edit request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_edit_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Announcement Edit Request',
                'verbose_name_plural': 'Announcement Edit Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='api_announc_status_e7dadc_idx'), models.Index(fields=['original_announcement', '-created_at'], name='api_announc_origina_402688_idx')],
            },
        ),
    ]
