# Generated by Django 5.2.5 on 2025-08-26 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_announcement_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementeditrequest',
            name='proposed_category',
            field=models.ForeignKey(blank=True, help_text='Proposed new category', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.announcementcategory', verbose_name='Proposed Category'),
        ),
        migrations.AlterField(
            model_name='announcementeditrequest',
            name='proposed_description',
            field=models.TextField(blank=True, help_text='Proposed new description', null=True, verbose_name='Proposed Description'),
        ),
        migrations.AlterField(
            model_name='announcementeditrequest',
            name='proposed_title',
            field=models.CharField(blank=True, help_text='Proposed new title', max_length=255, null=True, verbose_name='Proposed Title'),
        ),
        migrations.AlterField(
            model_name='announcementeditrequest',
            name='proposed_url',
            field=models.URLField(blank=True, help_text='Proposed new URL', null=True, verbose_name='Proposed URL'),
        ),
    ]
