# Generated by Django 5.2.5 on 2025-09-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_organizationdocument_rejection_reason_and_more'),
        ('api', '0016_alter_announcementeditrequest_proposed_category_and_more'),
    ]

    operations = [
    ]
