# Generated by Django 5.2.5 on 2025-09-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_merge_20250901_1029'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='api_notific_user_id_847a59_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_status',
        ),
        migrations.AddField(
            model_name='notification',
            name='shown',
            field=models.BooleanField(default=False, help_text='Has the notification been shown to user?', verbose_name='Shown Status'),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Date'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Notification title', max_length=255, verbose_name='Title'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'shown'], name='api_notific_user_id_c286ff_idx'),
        ),
    ]
