# Generated by Django 5.2.5 on 2025-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_notification_api_notific_user_id_847a59_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, default='defaults/announcement_default.png', null=True, upload_to='announcements/images/', verbose_name='Announcement Image'),
        ),
        migrations.AddField(
            model_name='organization',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/organization_default.png', null=True, upload_to='profile/organizations/', verbose_name='Organization Profile Image'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/user_default.png', null=True, upload_to='profile/users/', verbose_name='Profile Image'),
        ),
    ]
