# Generated by Django 5.2.5 on 2025-09-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_announcement_image_organization_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='profile_image',
        ),
    ]
