# Generated by Django 5.2.5 on 2025-09-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_organization_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_rejected',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='rejection_reason',
        ),
    ]
