# Generated by Django 5.2.5 on 2025-09-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_organization_is_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpsupport',
            name='priority',
        ),
        migrations.AddField(
            model_name='helpsupport',
            name='title',
            field=models.CharField(default='Support Request', max_length=100),
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='type',
            field=models.CharField(choices=[('system', 'System Issue'), ('organization', 'Organization Complaint'), ('other', 'Other')], default='system', max_length=20),
        ),
    ]
