# Generated by Django 5.2.5 on 2025-09-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_helpsupport_priority_helpsupport_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpsupport',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='helpsupport',
            name='status',
        ),
        migrations.AddField(
            model_name='announcementeditrequest',
            name='proposed_image',
            field=models.ImageField(blank=True, help_text='Proposed new image for the announcement', null=True, upload_to='announcements/images/', verbose_name='Proposed Image'),
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
