# Generated by Django 5.2.5 on 2025-09-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_helpsupport_reply_remove_helpsupport_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsupport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Organization')], default='pending', max_length=20),
        ),
    ]
