# Generated by Django 5.2.5 on 2025-09-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_helpsupport_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='api_notific_user_id_c286ff_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='shown',
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Organization'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user'], name='api_notific_user_id_145217_idx'),
        ),
    ]
