# Generated by Django 5.2.5 on 2025-09-09 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_helpsupport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpsupport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Organization'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='UserApplicationTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, help_text="User-provided application status (e.g., 'Applied', 'Interview scheduled', etc.)", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this application')),
                ('reminder_date', models.DateTimeField(blank=True, help_text='Date to remind user about follow-up', null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_applications', to='api.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_tracking', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Application Tracking',
                'verbose_name_plural': 'User Application Tracking',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['user', '-applied_at'], name='api_userapp_user_id_8407f5_idx'), models.Index(fields=['announcement', '-applied_at'], name='api_userapp_announc_c91e54_idx'), models.Index(fields=['status', '-applied_at'], name='api_userapp_status_a69332_idx'), models.Index(fields=['reminder_date'], name='api_userapp_reminde_9e804c_idx')],
                'unique_together': {('user', 'announcement')},
            },
        ),
    ]
