# Generated by Django 5.2.5 on 2025-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_helpsupport_status_userapplicationtracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapplicationtracking',
            options={'ordering': ['-created_at'], 'verbose_name': 'User Application Tracking', 'verbose_name_plural': 'User Application Tracking'},
        ),
        migrations.RemoveIndex(
            model_name='userapplicationtracking',
            name='api_userapp_user_id_8407f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='userapplicationtracking',
            name='api_userapp_announc_c91e54_idx',
        ),
        migrations.RemoveIndex(
            model_name='userapplicationtracking',
            name='api_userapp_status_a69332_idx',
        ),
        migrations.RenameField(
            model_name='userapplicationtracking',
            old_name='applied_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='userapplicationtracking',
            index=models.Index(fields=['user', '-created_at'], name='api_userapp_user_id_bd54eb_idx'),
        ),
        migrations.AddIndex(
            model_name='userapplicationtracking',
            index=models.Index(fields=['announcement', '-created_at'], name='api_userapp_announc_6bc034_idx'),
        ),
        migrations.AddIndex(
            model_name='userapplicationtracking',
            index=models.Index(fields=['status', '-created_at'], name='api_userapp_status_49e1a4_idx'),
        ),
    ]
