# Generated by Django 5.2.5 on 2025-09-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_userapplicationtracking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='profile_image',
            field=models.ImageField(blank=True, default='defaults/organization_default.png', null=True, upload_to='profile/organizations/', verbose_name='Organization Profile Image'),
        ),
    ]
