# Generated by Django 5.2.5 on 2025-09-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_notification_api_notific_user_id_c286ff_idx_and_more'),
        ('api', '0027_organization_profile_image'),
    ]

    operations = [
    ]
