# Generated by Django 5.2.5 on 2025-09-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_merge_20250930_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpsupport',
            name='target_org',
        ),
        migrations.AlterField(
            model_name='helpsupport',
            name='type',
            field=models.CharField(choices=[('system', 'System Issue'), ('other', 'Other')], default='system', max_length=20),
        ),
    ]
