# Generated by Django 5.2.5 on 2025-10-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_helpsupport_target_org_alter_helpsupport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpsupport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='AnnouncementEditRequest',
        ),
    ]
