# Generated by Django 5.2.5 on 2025-10-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_announcement_edit_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsupport',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
